batch:
  build-graph:
    - identifier: build1
      buildspec: batch-buildspec.yml
      env:
        variables:
          BUILD_ID: build1
      ignore-failure: true
    - identifier: build2
      buildspec: batch-buildspec.yml
      env:
        variables:
          BUILD_ID: build2
      depend-on:
        - build1
      ignore-failure: true
